const vocabDatabase = {
    "ep1": [
        // 1. 机场与交通
        { word: "Flygplats", trans: "Airport" },
        { word: "Tåg", trans: "Train" },
        { word: "Station", trans: "Station" },
        { word: "Centralstationen", trans: "Central station" },
        { word: "Skylt", trans: "Sign" },
        { word: "Skärm", trans: "Screen" },
        { word: "Band", trans: "Belt" },
        { word: "Spår", trans: "Track/Platform" },
        { word: "Väska", trans: "Bag/Suitcase" },
        
        // 2. Resor och biljettförsäljning
        { word: "Biljett", trans: "Ticket" },
        { word: "Enkelbiljett", trans: "One-way ticket" },
        { word: "Dagsbiljett", trans: "Day ticket" },
        { word: "Zon", trans: "Zone" },
        { word: "Rabatt", trans: "Discount" },
        { word: "Pris", trans: "Price" },
        { word: "Prisvärt", trans: "Affordable/Good value" },
        { word: "Direkt", trans: "Direct" },
        { word: "Byte", trans: "Change/Transfer" },
        { word: "Försenat", trans: "Delayed" },
        
        // 3. Riktning och verb
        { word: "Rakt fram", trans: "Straight ahead" },
        { word: "Till vänster", trans: "To the left" },
        { word: "Till höger", trans: "To the right" },
        { word: "Åka", trans: "Go/Ride" },
        { word: "Bo", trans: "Live" },
        { word: "Komma", trans: "Come" },
        { word: "Vänta", trans: "Wait" },
        { word: "Skynda sig", trans: "Hurry up" },
        
        // 4. Social etikett
        { word: "Namn", trans: "Name" },
        { word: "Jag heter...", trans: "My name is..." },
        { word: "Jag kommer från...", trans: "I come from..." },
        { word: "Jag bor i...", trans: "I live in..." },
        { word: "God dag", trans: "Good day" },
        { word: "Hej då", trans: "Goodbye" },
        { word: "Tack", trans: "Thanks" },
        { word: "Trevligt", trans: "Nice/Pleasant" },
        { word: "Välkommen", trans: "Welcome" }
        ],
    
    "ep2": [
       // 1. Boende & Miljö
        { word: "Radhus", trans: "Townhouse", audio: "v_radhus" },
        { word: "Lägenhet", trans: "Apartment", audio: "v_lagenhet" },
        { word: "Villa", trans: "Villa", audio: "v_villa" },
        { word: "Sovrum", trans: "Bedroom", audio: "v_sovrum" },
        { word: "Vardagsrum", trans: "Living room", audio: "v_vardagsrum" },
        { word: "Kök", trans: "Kitchen", audio: "v_kok" },
        { word: "Trädgård", trans: "Garden", audio: "v_tradgard" },
        { word: "Gräsmatta", trans: "Lawn", audio: "v_grasmatta" },
        { word: "Växter", trans: "Plants", audio: "v_vaxter" },

        // 2. Yrken
        { word: "Dataanalytiker", trans: "Data analyst", audio: "v_data" },
        { word: "Banktjänsteman", trans: "Bank clerk", audio: "v_bank" },
        { word: "Hemmafru", trans: "Housewife", audio: "v_hemmafru" },
        { word: "Grundskoleelev", trans: "Elementary school student", audio: "v_elev" },
        { word: "Förskolebarn", trans: "Preschooler", audio: "v_forskola" },

        // 3. Intressen
        { word: "Utomhussporter", trans: "Outdoor sports", audio: "v_sport" },
        { word: "Spela basket", trans: "Play basketball", audio: "v_basket" },
        { word: "Spela fotboll", trans: "Play soccer", audio: "v_fotboll" },
        { word: "Simma", trans: "Swim", audio: "v_simma" },
        { word: "Springa", trans: "Run", audio: "v_springa" },
        { word: "Lyssna på musik", trans: "Listen to music", audio: "v_musik" },
        { word: "Titta på film", trans: "Watch movie", audio: "v_film" },
        { word: "Tecknad film", trans: "Cartoon", audio: "v_tecknad" },
        { word: "Serier", trans: "Comics", audio: "v_serier" },
        { word: "Resa", trans: "Travel", audio: "v_resa" },
        { word: "Vandra", trans: "Hike", audio: "v_vandra" },
        { word: "Måla", trans: "Paint", audio: "v_mala" },
        { word: "Fiska", trans: "Fish", audio: "v_fiska" },
        { word: "Stickning", trans: "Knitting", audio: "v_sticka" },
        { word: "Sjunga", trans: "Sing", audio: "v_sjunga" },
        { word: "Spela piano", trans: "Play piano", audio: "v_piano" },
        { word: "Trädgårdsarbete", trans: "Gardening", audio: "v_tradgardarbete" },
        { word: "Matlagning", trans: "Cooking", audio: "v_matlagning" },
        { word: "Plocka bär", trans: "Pick berries", audio: "v_bara" },

        // 4. Transport
        { word: "Skolbuss", trans: "School bus", audio: "v_buss" },
        { word: "Cykel", trans: "Bicycle", audio: "v_cykel" },
        { word: "Bil", trans: "Car", audio: "v_bil" },
        { word: "Tåg", trans: "Train", audio: "v_tag2" },
        { word: "Tunnelbana", trans: "Subway", audio: "v_t-bana" },
        { word: "Gå", trans: "Walk", audio: "v_ga" },

        // 5. Väder och Årstider
        { word: "Vår", trans: "Spring", audio: "v_var" },
        { word: "Sommar", trans: "Summer", audio: "v_sommar" },
        { word: "Höst", trans: "Autumn", audio: "v_host" },
        { word: "Vinter", trans: "Winter", audio: "v_vinter" },
        { word: "Solig", trans: "Sunny", audio: "v_solig" },
        { word: "Kall", trans: "Cold", audio: "v_kall" },
        { word: "Varm", trans: "Hot", audio: "v_varm" },
        { word: "Sval", trans: "Cool", audio: "v_sval" },
        { word: "Blåsig", trans: "Windy", audio: "v_blasig" },
        { word: "Fuktig", trans: "Humid", audio: "v_fuktig" },
        { word: "Torr", trans: "Dry", audio: "v_torr" },
        { word: "Snöa", trans: "Snow", audio: "v_snoa" },
        { word: "Regna", trans: "Rain", audio: "v_regna" },

        // 6. Geografi och Länder
        { word: "Norra", trans: "North", audio: "v_norra" },
        { word: "Södra", trans: "South", audio: "v_sodra" },
        { word: "Östra", trans: "East", audio: "v_ostra" },
        { word: "Västra", trans: "West", audio: "v_vastra" },
        { word: "Sverige", trans: "Sweden", audio: "v_sverige" },
        { word: "Kina", trans: "China", audio: "v_kina" },
        { word: "Italien", trans: "Italy", audio: "v_italien" },
        { word: "Spanien", trans: "Spain", audio: "v_spanien" },
        { word: "Frankrike", trans: "France", audio: "v_frankrike" },
        { word: "Tyskland", trans: "Germany", audio: "v_tyskland" }
    ],

   "ep3": [
        { word: "Mataffär", trans: "Supermarket" },
        { word: "Handla", trans: "Shop (for groceries)" },
        { word: "Inköpslista", trans: "Shopping list" },
        { word: "Kundvagn", trans: "Shopping cart" },
        { word: "Kundkorg", trans: "Shopping basket" },
        { word: "Avdelning", trans: "Section/Department" },
        { word: "Potatis", trans: "Potato" },
        { word: "Morot", trans: "Carrot" },
        { word: "Lök", trans: "Onion" },
        { word: "Tomat", trans: "Tomato" },
        { word: "Gurka", trans: "Cucumber" },
        { word: "Sallad", trans: "Lettuce" },
        { word: "Broccoli", trans: "Broccoli" },
        { word: "Champinjon", trans: "Mushroom" },
        { word: "Vitlök", trans: "Garlic" },
        { word: "Paprika", trans: "Bell pepper" },
        { word: "Vitkål", trans: "Cabbage" },
        { word: "Äpple", trans: "Apple" },
        { word: "Banan", trans: "Banana" },
        { word: "Vindruvor", trans: "Grapes" },
        { word: "Persika", trans: "Peach" },
        { word: "Citron", trans: "Lemon" },
        { word: "Vattenmelon", trans: "Watermelon" },
        { word: "Jordgubbar", trans: "Strawberries" },
        { word: "Blåbär", trans: "Blueberries" },
        { word: "Körsbär", trans: "Cherries" },
        { word: "Apelsin", trans: "Orange" },
        { word: "Nötkött", trans: "Beef" },
        { word: "Fläskkött", trans: "Pork" },
        { word: "Kyckling", trans: "Chicken" },
        { word: "Lamm", trans: "Lamb" },
        { word: "Bacon", trans: "Bacon" },
        { word: "Skinka", trans: "Ham" },
        { word: "Mjölk", trans: "Milk" },
        { word: "Yoghurt", trans: "Yogurt" },
        { word: "Ägg", trans: "Eggs" },
        { word: "Ost", trans: "Cheese" },
        { word: "Smör", trans: "Butter" },
        { word: "Grädde", trans: "Cream" },
        { word: "Glass", trans: "Ice cream" },
        { word: "Pizza", trans: "Pizza" },
        { word: "Hamburgare", trans: "Hamburger" },
        { word: "Choklad", trans: "Chocolate" },
        { word: "Godis", trans: "Candy" },
        { word: "Kakor", trans: "Cookies" },
        { word: "Chips", trans: "Potato chips" },
        { word: "Te", trans: "Tea" },
        { word: "Kaffe", trans: "Coffee" },
        { word: "Extrapris", trans: "Special offer" },
        { word: "Ekologisk", trans: "Organic" },
        { word: "Laktosfri", trans: "Lactose-free" },
        { word: "Vegansk", trans: "Vegan" },
        { word: "Svensk", trans: "Swedish (product)" },
        { word: "Importerad", trans: "Imported" },
        { word: "Självscanning", trans: "Self-checkout" },
        { word: "Skanna", trans: "Scan" },
        { word: "Streckkod", trans: "Barcode" },
        { word: "Väga", trans: "Weigh" },
        { word: "Medlemskort", trans: "Membership card" },
        { word: "Kvitto", trans: "Receipt" },
        { word: "Spara", trans: "Save (money)" },
        { word: "Pant", trans: "Bottle deposit" },
        { word: "Pantmaskin", trans: "Bottle return machine" },
        { word: "Flaska", trans: "Bottle" },
        { word: "Burk", trans: "Can" },
        { word: "Återvinna", trans: "Recycle" },
        { word: "Pengar tillbaka", trans: "Money back / Refund" }
     ],

   "ep4": [
        // 1. Bankgrunder – Bank Basics
        { word: "en bank", trans: "a bank" },
        { word: "ett bankkonto", trans: "a bank account" },
        { word: "ett konto", trans: "an account" },
        { word: "en kund", trans: "a customer" },
        { word: "en bankkund", trans: "a bank customer" },
        { word: "en bankanställd", trans: "a bank employee" },
        { word: "en banktjänsteman", trans: "a bank officer" },
        { word: "en tjänst", trans: "a service" },
        { word: "en bankapp", trans: "a banking app" },
        { word: "mobilbanken", trans: "mobile banking" },

        // 2. Olika typer av konton – Types of Accounts
        { word: "ett lönekonto", trans: "salary account" },
        { word: "ett transaktionskonto", trans: "transaction account" },
        { word: "ett privatkonto", trans: "personal account" },
        { word: "ett sparkonto", trans: "savings account" },
        { word: "ett ISK-konto", trans: "investment savings account" },
        { word: "ett investeringskonto", trans: "investment account" },
        { word: "ett pensionskonto", trans: "pension account" },

        // 3. Lön och vardagsekonomi – Salary & Daily Money
        { word: "en lön", trans: "salary" },
        { word: "en månadslön", trans: "monthly salary" },
        { word: "få lön", trans: "receive salary" },
        { word: "sätta in pengar", trans: "deposit money" },
        { word: "ta ut pengar", trans: "withdraw money" },
        { word: "överföra pengar", trans: "transfer money" },
        { word: "en överföring", trans: "a transfer" },
        { word: "ett saldo", trans: "balance" },
        { word: "ett kontoutdrag", trans: "bank statement" },
        { word: "tillgängliga pengar", trans: "available money" },

        // 4. Betala räkningar – Paying Bills
        { word: "en räkning", trans: "a bill" },
        { word: "en faktura", trans: "an invoice" },
        { word: "betala en räkning", trans: "pay a bill" },
        { word: "en betalning", trans: "a payment" },
        { word: "betalningar", trans: "payments" },
        { word: "ett belopp", trans: "an amount" },
        { word: "en mottagare", trans: "a recipient" },
        { word: "ett bankgiro", trans: "bank giro number" },
        { word: "ett plusgiro", trans: "plus giro number" },
        { word: "ett OCR-nummer", trans: "OCR reference number" },
        { word: "förfallodatum", trans: "due date" },
        { word: "godkänna", trans: "approve" },

        // 5. BankID och digitala tjänster – BankID & Digital Banking
        { word: "BankID", trans: "digital ID" },
        { word: "logga in", trans: "log in" },
        { word: "logga ut", trans: "log out" },
        { word: "identifiera sig", trans: "identify oneself" },
        { word: "signera", trans: "sign" },
        { word: "en säkerhetskod", trans: "security code" },
        { word: "ett lösenord", trans: "password" },
        { word: "säker", trans: "safe / secure" },
        { word: "försiktig", trans: "careful" },
        { word: "ett bedrägeri", trans: "fraud" },

        // 6. Spara pengar – Saving Money
        { word: "spara", trans: "save" },
        { word: "ett sparande", trans: "saving" },
        { word: "månadsspara", trans: "save monthly" },
        { word: "långsiktigt sparande", trans: "long-term saving" },
        { word: "kortsiktigt sparande", trans: "short-term saving" },
        { word: "en ränta", trans: "interest rate" },
        { word: "en avkastning", trans: "return" },
        { word: "växa", trans: "grow" },
        { word: "pengar växer", trans: "money grows" },

        // 7. Investera och Avanza – Investing & Avanza
        { word: "investera", trans: "invest" },
        { word: "en investering", trans: "investment" },
        { word: "en investerare", trans: "investor" },
        { word: "en fond", trans: "fund" },
        { word: "en aktie", trans: "stock / share" },
        { word: "en indexfond", trans: "index fund" },
        { word: "en globalfond", trans: "global fund" },
        { word: "en portfölj", trans: "portfolio" },
        { word: "ett värdepapper", trans: "security" },
        { word: "en marknad", trans: "market" },

        // 8. Köpa och sälja – Buying & Selling
        { word: "köpa", trans: "buy" },
        { word: "sälja", trans: "sell" },
        { word: "en köporder", trans: "buy order" },
        { word: "en säljorder", trans: "sell order" },
        { word: "lägga en order", trans: "place an order" },
        { word: "välja", trans: "choose" },
        { word: "söka efter", trans: "search for" },
        { word: "belopp", trans: "amount" },
        { word: "antal", trans: "number / quantity" },
        { word: "pris", trans: "price" },
        { word: "kurs", trans: "price / rate" },

        // 9. Fondavgifter och risker – Fund Fees & Risks
        { word: "en avgift", trans: "a fee" },
        { word: "låg avgift", trans: "low fee" },
        { word: "hög avgift", trans: "high fee" },
        { word: "en risk", trans: "a risk" },
        { word: "risknivå", trans: "risk level" },
        { word: "värde", trans: "value" },
        { word: "minska", trans: "decrease" },
        { word: "öka", trans: "increase" },
        { word: "gå upp", trans: "go up" },
        { word: "gå ner", trans: "go down" },

        // 10. Vanliga verb – Common Verbs
        { word: "öppna", trans: "open" },
        { word: "stänga", trans: "close" },
        { word: "använda", trans: "use" },
        { word: "betala", trans: "pay" },
        { word: "köpa", trans: "buy" },
        { word: "sälja", trans: "sell" },
        { word: "spara", trans: "save" },
        { word: "investera", trans: "invest" },
        { word: "välja", trans: "choose" },
        { word: "kontrollera", trans: "check" },
        { word: "förstå", trans: "understand" },
        { word: "lära sig", trans: "learn" }
    ]
};
